private _checks = 0;
private _assert = {params ["_ok","_name"]; if (!_ok) then {throw _name}; _checks = _checks + 1};
private _clear = [100,1000,1,1,1,1,0.5,1] call HUNCH_fnc_score;
private _far = [900,1000,1,1,1,1,0.5,1] call HUNCH_fnc_score;
private _masked = [100,1000,0.25,0.35,0.7,0.4,0.5,1] call HUNCH_fnc_score;
[(_clear select 0) > (_far select 0),"range reduces noticeability"] call _assert;
[(_masked select 1) < (_clear select 1),"cover and masking reduce confidence"] call _assert;
[(_masked select 3) > (_clear select 3),"low confidence broadens error"] call _assert;
private _silent = [1000,1000,1,1,1,1,1,2] call HUNCH_fnc_score;
[(_silent select 0) == 0 && {(_silent select 2) == 0},"outside range never sampled"] call _assert;
private _strong = [0,1000,1,1,1,1,1,2] call HUNCH_fnc_score;
[(_strong select 2) <= 0.85 && {(_strong select 1) <= 0.85},"certainty and probability capped"] call _assert;
private _muted = [100,1000,1,1,1,1,1,0] call HUNCH_fnc_score;
[(_muted select 2) == 0,"frequency zero disables sound sampling"] call _assert;
[[0] call HUNCH_fnc_envelope == 0,"transparent at birth"] call _assert;
[[0.15] call HUNCH_fnc_envelope == 1,"peak after fade in"] call _assert;
[[1.2] call HUNCH_fnc_envelope == 0,"expired transparent"] call _assert;
private _budget = [[0.15,0.15,0.15],0.15] call HUNCH_fnc_alphaBudget;
private _sum = 0; {_sum = _sum + _x} forEach _budget;
[_sum <= 0.150001,"overlapping spots obey cap"] call _assert;
private _combined = [[0.15,0.4,0.4],0.4] call HUNCH_fnc_alphaBudget;
private _composite = 1; {_composite = _composite * (1 - _x)} forEach _combined;
[1 - _composite <= 0.4,"dots and spots cannot exceed hard opacity ceiling"] call _assert;
private _window = [0,343,0.5] call HUNCH_fnc_audioWindow;
[(_window select 0) == 1 && {_window select 1},"sound arrives after one second at 343m"] call _assert;
[!(([0,343,2.51] call HUNCH_fnc_audioWindow) select 1),"late impact cannot resurrect old report"] call _assert;
[[5,355] call HUNCH_fnc_angleDelta == 10,"bearing wraps north"] call _assert;
private _north = [0,0] call HUNCH_fnc_direction;
[abs (_north select 0) < 0.001 && {abs ((_north select 1) - 1) < 0.001},"bearing north projects correctly"] call _assert;
HUNCH_seed = 123;
private _a = []; for "_i" from 1 to 100 do {_a pushBack call HUNCH_fnc_random};
HUNCH_seed = 123;
private _b = []; for "_i" from 1 to 100 do {_b pushBack call HUNCH_fnc_random};
[_a isEqualTo _b,"seeded observation sampling is reproducible"] call _assert;
[(_a findIf {_x < 0 || {_x >= 1}}) == -1,"random values are bounded"] call _assert;
private _notices = 0;
HUNCH_seed = 123;
for "_i" from 1 to 1000 do {if ((call HUNCH_fnc_random) < 0.4) then {_notices = _notices + 1}};
[_notices > 340 && {_notices < 460},"sampling statistical sanity"] call _assert;
private _center = [[0.5,0.5],[0,0,1],[0.4,0.4]] call HUNCH_fnc_layout;
[(_center select 0) && {(_center select 1) == 0},"central report stays in scene"] call _assert;
private _edge = [[0.95,0.5],[1,0,1],[0.4,0.4]] call HUNCH_fnc_layout;
[(_edge select 1) > 0 && {(_edge select 1) < 1},"uncertainty crossing view edge blends"] call _assert;
private _behind = [[],[0,0,-1],[0.4,0.4]] call HUNCH_fnc_layout;
[(_behind select 2) isEqualTo [0.5,1],"direct rear maps to bottom border"] call _assert;
private _left = [[],[-1,0,0],[0.4,0.4]] call HUNCH_fnc_layout;
[(_left select 2) isEqualTo [0,0.5],"out of view left maps to left border"] call _assert;
private _deaf = [0,0,1,1,1,1,1,1] call HUNCH_fnc_score;
[(_deaf select 0) == 0,"zero hearing range cannot create a colocated audio cue"] call _assert;
diag_log format ["HUNCH_MATH_PASS checks=%1",_checks];
