private _checks = 0;
private _assert = {params ["_ok","_name"]; if (!_ok) then {throw _name}; _checks = _checks + 1};
HUNCH_controls = [];
HUNCH_metrics = createHashMap;
HUNCH_cost = 0;
call HUNCH_fnc_reset;
HUNCH_effective = true;
private _source = "O_Soldier_F" createVehicle [0,100,0];
private _projectile = "B_65x39_Caseless" createVehicle [0,1,1];
_projectile setVariable ["HUNCH_shotId","1:1"];
[_source,_projectile,"B_65x39_Caseless","near",_source] call HUNCH_fnc_incoming;
[count HUNCH_pending == 1,"incoming evidence queues one observation"] call _assert;
[_source,_projectile,"B_65x39_Caseless","hit",_source] call HUNCH_fnc_incoming;
[count HUNCH_pending == 1,"near and hit notifications deduplicate"] call _assert;
[_source,objNull,"B_65x39_Caseless","hit",_source] call HUNCH_fnc_incoming;
[count HUNCH_pending == 1,"null projectile never guesses source context"] call _assert;
HUNCH_effective = false;
_projectile setVariable ["HUNCH_shotId","1:2"];
[_source,_projectile,"B_65x39_Caseless","near",_source] call HUNCH_fnc_incoming;
[count HUNCH_pending == 1,"inactive addon ignores incoming fire"] call _assert;
HUNCH_effective = true;
HUNCH_pending = []; for "_i" from 1 to 32 do {HUNCH_pending pushBack [str _i,time,"near"]};
[_source,_projectile,"B_65x39_Caseless","near",_source] call HUNCH_fnc_incoming;
[count HUNCH_pending == 32,"queue saturation remains bounded"] call _assert;
private _cue = ["a","sound",[0,1,0],[40,30],0.5,0.6,[1,0.7,0.4],time,time+1.2];
[_cue] call HUNCH_fnc_emit;
[_cue] call HUNCH_fnc_emit;
[count HUNCH_cues == 1,"overlap merges instead of stacking"] call _assert;
private _other = ["b","sound",[1,0,0],[40,30],0.6,0.9,[1,0.7,0.4],time,time+1.2];
[_other] call HUNCH_fnc_emit;
[count HUNCH_cues == 1,"global rate limit suppresses third observation"] call _assert;
HUNCH_rates = [];
[_other] call HUNCH_fnc_emit;
[count HUNCH_cues == 2,"independent directions coexist below limits"] call _assert;
private _dot = ["d","flash",[1,0,0],[0,0],1,1,[0,0,0],time,time+0.15];
[_dot] call HUNCH_fnc_emit; [_dot] call HUNCH_fnc_emit; [_dot] call HUNCH_fnc_emit;
[count HUNCH_dots == 2,"flash pool stays bounded"] call _assert;
private _generation = HUNCH_generation;
HUNCH_shots set ["old",createHashMap];
call HUNCH_fnc_reset;
[count HUNCH_cues == 0 && {count HUNCH_dots == 0} && {count HUNCH_pending == 0},"reset clears every transient visual and queue"] call _assert;
[count HUNCH_shots == 0 && {count HUNCH_seen == 0} && {count HUNCH_episodes == 0},"reset clears observations and episodes"] call _assert;
[HUNCH_generation > _generation,"reset generation prevents old projectile id collision"] call _assert;
diag_log format ["HUNCH_RUNTIME_PASS checks=%1",_checks];
