disableSerialization;
{ctrlDelete _x} forEach HUNCH_controls;
HUNCH_controls = [];
HUNCH_shots = createHashMap;
HUNCH_shotOrder = [];
HUNCH_pending = [];
HUNCH_seen = createHashMap;
HUNCH_episodes = createHashMap;
HUNCH_cues = [];
HUNCH_dots = [];
HUNCH_rates = [];
HUNCH_rayTimes = [];
HUNCH_noise = [];
HUNCH_lastOwn = -100;
HUNCH_lastSweep = -100;
HUNCH_lastDiagnostic = time;
HUNCH_serial = 0;
HUNCH_generation = (missionNamespace getVariable ["HUNCH_generation",0]) + 1;
HUNCH_effective = false;
HUNCH_degraded = false;
HUNCH_recoverAt = -1;
HUNCH_overBudgetFrames = 0;
HUNCH_controlDisplay = displayNull;
